// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/login","layout":false,"id":"1"},"2":{"path":"/register","layout":false,"id":"2"},"3":{"path":"/","parentId":"@@/global-layout","id":"3"},"4":{"path":"/","parentId":"3","id":"4"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__login" */'@/pages/login.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__register" */'@/pages/register.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'@/layouts/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__index" */'@/pages/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/app/react-admin/src/layouts/index.tsx')),
},
  };
}
