name: yudao-ui-admin-vue3 CI

on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

env:
  TZ: Asia/Shanghai
  WORK_DIR: .

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.15.1

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'pnpm'
          cache-dependency-path: ./pnpm-lock.yaml

      - name: Install dependencies
        run: |
          node --version
          pnpm --version
          pnpm install

      - name: Build
        run: pnpm build:prod
